spring:
  profiles:
    active: ${profile.active}
  main:
    banner-mode: off
mybatis-plus:
  global-config:
    banner: false
    logic-delete-field: flag
    logic-delete-value: true
    logic-not-delete-value: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
server:
  port: 8001
credentials:
  secret-key: u8dh39hd9312
  salt: 89j3@129%

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6380
server:
  port: 8081
credentials:
  secret-key: u8dh39hd9312
  salt: 89j3@129%

---